typography_spectrum: 0.5413647361565381
color:
  saturation: 0.8288393507245928
  brandStrength: 0.8149860459379852
  rhythmicContrast: 0.7745898386929184
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  lightness: 0.09272078284993768
layout_spectrum: 0.9173693
name: Göttinger Pál m.v.
navigation:
  - name: web
    url: 'http://www.gottingerpal.com'
    type: external
  - name: facebook
    url: 'https://www.facebook.com/gottingerpalmv/'
    type: external
  - name: twitter
    url: 'https://twitter.com/deltenger'
    type: external
  - name: google+
    url: 'https://plus.google.com/+G%C3%B6ttingerP%C3%A1lmv'
    type: external
  - name: linkedin
    url: 'https://hu.linkedin.com/in/p%C3%A1l-g%C3%B6ttinger-0694a84'
    type: external
  - name: flickr
    url: flickr
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Más olvasnivaló
description: www.gottingerpal.com
