layout_spectrum: 0.7162666434887797
typography_spectrum: 0.39924223767593503
color:
  saturation: 0.41990341641940176
  brandStrength: 0.3100880333222449
  lightness: 0.7414035638794303
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
  rhythmicContrast: 0.8451522188261151
name: Göttinger Pál m.v.
navigation:
  - name: web
    url: 'http://www.gottingerpal.com'
    type: external
  - name: facebook
    url: 'https://www.facebook.com/gottingerpalmv/'
    type: external
  - name: twitter
    url: 'https://twitter.com/deltenger'
    type: external
  - name: google+
    url: 'https://plus.google.com/+G%C3%B6ttingerP%C3%A1lmv'
    type: external
  - name: linkedin
    url: 'https://hu.linkedin.com/in/p%C3%A1l-g%C3%B6ttinger-0694a84'
    type: external
  - name: flickr
    url: 'https://www.flickr.com/photos/gottingerpal/'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Más olvasnivaló
description: www.gottingerpal.com
