typography_spectrum: 0.3144190516322851
color:
  saturation: 0.026802444830536842
  brandStrength: 0.6202174664940685
  lightness: 0.4712082748301327
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  rhythmicContrast: 0.23328685108572245
layout_spectrum: 0.7162666434887797
name: Göttinger Pál m.v.
navigation:
  - name: web
    url: 'http://www.gottingerpal.com'
    type: external
  - name: facebook
    url: 'https://www.facebook.com/gottingerpalmv/'
    type: external
  - name: twitter
    url: 'https://twitter.com/deltenger'
    type: external
  - name: google+
    url: 'https://plus.google.com/+G%C3%B6ttingerP%C3%A1lmv'
    type: external
  - name: linkedin
    url: 'https://hu.linkedin.com/in/p%C3%A1l-g%C3%B6ttinger-0694a84'
    type: external
  - name: flickr
    url: 'https://www.flickr.com/photos/gottingerpal/'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Más olvasnivaló
description: www.gottingerpal.com
