title: Más olvasnivaló
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8288393507245928
  brandStrength: 0.8149860459379852
  lightness: 0.09272078284993768
  brandColors:
    - '#020202'
    - '#E8E7E6'
    - '#9A9C97'
    - '#464538'
    - '#4481D2'
  rhythmicContrast: 0.7745898386929184
typography_spectrum: 0.2775689
description: www.gottingerpal.com
navigation:
  - name: Weboldal
    url: 'http://www.gottingerpal.com'
    type: external
layout_spectrum: 1
name: Göttinger Pál m.v.
