layout_spectrum: 0.9173693
typography_spectrum: 0.33965943311341107
color:
  saturation: 0.22579952236264944
  brandStrength: 0.936862833565101
  rhythmicContrast: 0.07352803461253643
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  lightness: 0.6635656154248863
title: Más olvasnivaló
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: www.gottingerpal.com
navigation:
  - name: Weboldal
    url: 'http://www.gottingerpal.com'
    type: external
name: Göttinger Pál m.v.
