typography_spectrum: 0.5413647361565381
color:
  brandStrength: 0.8149860459379852
  lightness: 0.09272078284993768
  saturation: 0.8288393507245928
  rhythmicContrast: 0.7745898386929184
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.9112930120900273
name: Göttinger Pál m.v.
navigation:
  - name: Weboldal
    url: 'http://www.gottingerpal.com'
    type: external
title: Más olvasnivaló
description: www.gottingerpal.com
